[package]
name = "pushback-iter"
version = "0.1.0"
authors = ["Jason Hinch <594559+jhinch@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
